# Generated by Django 4.1.5 on 2023-01-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
